# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "BadBoids"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: Caribou

database: /home/badboids/database/store.sqlite

session: YAML
session_dir: /home/badboids/sessions

serializer: JSON

engines:
    JSON:
        allow_blessed:   1
        canonical:       '1'
        convert_blessed: '1'


plugins:
    "Auth::Twitter":
        consumer_key:     "hush"
        consumer_secret:  "secret"
        callback_url:     "http://enkidu.babyl.ca:3000/auth/twitter/callback"
        callback_success: "/authorized"
        callback_fail:    "/fail"
    "Auth::Extensible":
        disable_roles: 1
        realms:
            users:
                provider: Config
                users:
                    - user: yanick
                      pass: secret

